[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback so client-side routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
